const sections=[['Beneficjent',['id','data','beneficjent','adres','dzialka','miejscowosc','kod','ppe','telefon','email','wykonawca']],['Instalacja elektryczna',['mocPrzyl','zabezpieczenie','mocUmowna','fazy','siec','zasilanie','licznik','rozdzielnica','typZab','rcd','ppoz','odgrom']],['Istniejąca i planowana PV',['istPV','istMoc','istModuly','istFalownik','rodzaj','liczbaMod','mocPV','modelMod','mocME','pojemnoscME','modelME','falownik']],['Miejsce montażu',['miejsce','wysokosc','pokrycie','material','rozstaw','konstrukcja','dachH','dachX','dachY','kalenica','krawedz','kat','ogniomur','przekop','przekopM']],['Falownik i magazyn energii',['lokFal','lokME','wpięcie','temp','ogrzewane','internet','trasaAC','trasaDC','uwagi']]];
const labels={id:'ID wizji',data:'Data wizji',beneficjent:'Beneficjent',adres:'Adres montażu',dzialka:'Numer działki',miejscowosc:'Miejscowość',kod:'Kod pocztowy',ppe:'Numer PPE',telefon:'Telefon',email:'E-mail',wykonawca:'Przedstawiciel wykonawcy',mocPrzyl:'Moc przyłączeniowa [kW]',zabezpieczenie:'Zabezpieczenie przedlicznikowe [A]',mocUmowna:'Moc umowna [kW]',fazy:'Liczba faz',siec:'Typ sieci',zasilanie:'Sposób zasilania',licznik:'Lokalizacja licznika',rozdzielnica:'Lokalizacja rozdzielnicy',typZab:'Typ zabezpieczenia',rcd:'RCD',ppoz:'Wyłącznik ppoż.',odgrom:'Instalacja odgromowa',istPV:'Istniejąca PV',istMoc:'Moc istniejącej PV',istModuly:'Istniejące moduły',istFalownik:'Istniejący falownik',rodzaj:'Rodzaj inwestycji',liczbaMod:'Liczba modułów',mocPV:'Moc PV [kWp]',modelMod:'Model / moc modułów',mocME:'Moc ME [kW]',pojemnoscME:'Pojemność ME [kWh]',modelME:'Model ME',falownik:'Planowany falownik',miejsce:'Miejsce montażu',wysokosc:'Wysokość budynku [m]',pokrycie:'Pokrycie dachu',material:'Materiał krokwi/płatwi',rozstaw:'Rozstaw krokwi [cm]',konstrukcja:'Konstrukcja / stan dachu',dachH:'Dach h [m]',dachX:'Dach x [m]',dachY:'Dach y [m]',kalenica:'Kalenica [m]',krawedz:'Krawędź [m]',kat:'Kąt dachu [°]',ogniomur:'Ogniomur',przekop:'Przekop',przekopM:'Długość przekopu [m]',lokFal:'Lokalizacja falownika',lokME:'Lokalizacja ME',wpięcie:'Miejsce wpięcia',temp:'Temperatura min. +5°C',ogrzewane:'Pomieszczenie ogrzewane',internet:'Zasięg Internetu',trasaAC:'Trasa przewodów AC',trasaDC:'Trasa przewodów DC',uwagi:'Uwagi techniczne'};
const GOOGLE_API_URL='https://script.google.com/macros/s/AKfycbwgc0QVUhMsHYtW5lbV3-cWKRSQEUGfvxqXGkAvL_2ORBOTIqreJDdi9RwVHbNT5BzV/exec';
function apiUrl(){return GOOGLE_API_URL}
const choiceOptions={
 fazy:['1F','3F'],siec:['TN-S','TN-C','TN-C-S','TT','IT','Nie ustalono'],zasilanie:['Kablowe','Napowietrzne','Nie ustalono'],
 typZab:['Wyłącznik nadprądowy','Bezpiecznik topikowy','Rozłącznik bezpiecznikowy','Inne','Nie ustalono'],
 rcd:['Tak','Nie','Nie dotyczy','Nie ustalono'],ppoz:['Tak','Nie','Nie dotyczy','Nie ustalono'],odgrom:['Tak','Nie','Nie ustalono'],
 istPV:['Tak','Nie','Nie ustalono'],rodzaj:['PV','PV+ME','PV+ME, PC','PV, PC','ME','PC','Inny'],
 miejsce:['Dach','Dach skośny','Dach płaski','Grunt','Elewacja','Inne'],pokrycie:['Dachówka ceramiczna','Dachówka betonowa','Blachodachówka','Blacha trapezowa','Rąbek stojący','Papa','Membrana','Gont','Inne'],
 ogniomur:['Tak','Nie','Nie dotyczy','Nie ustalono'],przekop:['Tak','Nie','Nie dotyczy','Nie ustalono'],
 temp:['Tak','Nie','Nie ustalono'],ogrzewane:['Tak','Nie','Nie ustalono'],internet:['Tak','Nie','Słaby zasięg','Brak zasięgu','Nie ustalono']
};
let state=JSON.parse(localStorage.getItem('currentSurvey')||'{}');let screen='home',step=0,photos=[];const app=document.querySelector('#app');
function save(){localStorage.setItem('currentSurvey',JSON.stringify(state));}
function header(title){return `<header class="top"><button class="brandHome noPrint" aria-label="Przejdź do menu" onclick="goHome()"><img src="nasz-prad-logo.png" alt="Nasz Prąd S.A."></button><div class="headerTitle"><h1>${title}</h1><span><i></i> Google i zapis lokalny</span></div></header>`}
function field(k){let big=/uwagi|konstrukcja|trasa/.test(k),opts=choiceOptions[k],current=String(state[k]||'');if(opts){let list=current&&!opts.includes(current)?[current,...opts]:opts;return `<div class="field choiceField"><label for="field-${k}">${labels[k]}</label><div class="selectWrap"><select id="field-${k}" data-k="${k}" aria-label="${labels[k]}"><option value="">— wybierz z listy —</option>${list.map(v=>`<option value="${escapeHtml(v)}" ${current===v?'selected':''}>${escapeHtml(v)}</option>`).join('')}</select></div></div>`}return `<div class="field ${big?'full':''}"><label for="field-${k}">${labels[k]}</label>${big?`<textarea id="field-${k}" data-k="${k}">${escapeHtml(state[k]||'')}</textarea>`:`<input id="field-${k}" data-k="${k}" value="${escapeHtml(state[k]||'')}">`}</div>`}
let cloudTimer=null;
function bind(){document.querySelectorAll('[data-k]').forEach(x=>x.oninput=()=>{state[x.dataset.k]=x.value;save();scheduleCloudSave();if(x.dataset.k==='istPV')form()})}
function render(){if(screen==='home')return home();if(screen==='form')return form();if(screen==='map')return mapEditor();if(screen==='photos')return photoScreen();if(screen==='sign')return signatures();if(screen==='summary')return summary()}
function home(){app.innerHTML=header('Wizja lokalna')+`<main class="wrap homeWrap"><section class="intro"><h2>Ankieta instalacji PV i magazynu energii</h2><p>Rozpocznij od wskazania Beneficjenta. Dane kontaktowe oraz przydzielone urządzenia zostaną pobrane automatycznie.</p><button class="btn primary startBtn" onclick="newSurvey()">Rozpocznij nową ankietę <span>→</span></button></section><div class="status"><b>Połączono z Arkuszem Google</b><span>Autozapis do zakładki ODPOWIEDZI jest włączony.</span></div><section class="card quickCard"><h2>Elementy ankiety</h2><div class="menu"><button onclick="newSurvey()"><span>01</span>Wybór Beneficjenta</button><button onclick="openMap()"><span>02</span>Mapa i moduły</button><button onclick="openPhotos()"><span>03</span>Zdjęcia</button><button onclick="openSign()"><span>04</span>Podpisy</button></div></section><div id="saved"></div></main>`;renderSaved()}
function renderSaved(){let arr=JSON.parse(localStorage.getItem('surveys')||'[]');document.querySelector('#saved').innerHTML=arr.length?`<div class="card"><h2>Zapisane ankiety</h2>${arr.map((x,i)=>`<div class="listItem"><b>${x.beneficjent||'Bez nazwy'}</b><div class="muted">${x.adres||''} · ${x.data||''}</div><button class="btn" onclick="loadSurvey(${i})">Otwórz</button></div>`).join('')}</div>`:''}
function selectedBeneficiaryCard(){if(!state.sourceBeneficiaryId)return'';return `<div class="selectedBeneficiary"><div class="selectedMark">✓</div><div><small>Wybrany Beneficjent</small><h3>${escapeHtml(state.beneficjent||'')}</h3><p>${escapeHtml(state.adres||'')}${state.miejscowosc?' · '+escapeHtml(state.miejscowosc):''}</p><p><b>Telefon:</b> ${escapeHtml(state.telefon||'brak')} ${state.sourceContract?`<b class="contract">Umowa:</b> ${escapeHtml(state.sourceContract)}`:''}</p><div class="deviceSummary"><span><b>${escapeHtml(state.rodzaj||'Zakres nieokreślony')}</b>Zakres</span><span><b>${escapeHtml(state.liczbaMod||'—')}</b>Liczba modułów</span><span><b>${escapeHtml(state.mocPV||'—')}</b>Moc PV</span><span><b>${escapeHtml(state.falownik||'—')}</b>Falownik</span><span><b>${escapeHtml(state.pojemnoscME||'—')}</b>Magazyn energii</span><span><b>${escapeHtml(state.modelME||'—')}</b>Model magazynu</span></div></div></div>`}
function visibleKeys(keys){return keys.filter(k=>!(step===2&&state.istPV==='Nie'&&['istMoc','istModuly','istFalownik'].includes(k)))}
function form(){let [title,keys]=sections[step],picker=step===0?`<section class="beneficiaryPanel"><div class="stepHeading"><span>1</span><div><h2>Wybierz Beneficjenta</h2><p>Wyszukaj po nazwisku, adresie, miejscowości lub numerze umowy.</p></div></div><div class="beneficiarySearch"><span aria-hidden="true">⌕</span><input id="beneficiaryQuery" oninput="searchBeneficiaries(this.value)" placeholder="Zacznij wpisywać dane Beneficjenta" autocomplete="off"></div><p class="sourceNote">Dane pobierane z <b>REALIZACJA – AKTUALIZOWANA</b></p><div id="beneficiaryResults"></div>${selectedBeneficiaryCard()}</section>`:'';let detailsTitle=step===0?'Dane pobrane z arkusza':title;app.innerHTML=header(title)+`<main class="wrap"><div class="progress" aria-label="Postęp ankiety">${sections.map((_,i)=>`<i class="${i<=step?'on':''}"></i>`).join('')}</div>${picker}<section class="card formCard ${step===0&&!state.sourceBeneficiaryId?'pendingDetails':''}"><h2>${detailsTitle}</h2>${step===0&&!state.sourceBeneficiaryId?'<p class="emptyDetails">Najpierw wyszukaj i wybierz Beneficjenta. Imię, nazwisko, telefon, adres oraz urządzenia zostaną uzupełnione automatycznie.</p>':`<div class="grid">${visibleKeys(keys).map(field).join('')}</div>`}</section></main><footer class="actions"><div><button class="btn" onclick="prev()">Wstecz</button><button class="btn primary" ${step===0&&!state.sourceBeneficiaryId?'disabled':''} onclick="next()">${step===sections.length-1?'Mapa i moduły':'Dalej'}</button></div></footer>`;bind()}
let beneficiaryTimer=null,beneficiaryCache=[];
function searchBeneficiaries(q){clearTimeout(beneficiaryTimer);let box=document.querySelector('#beneficiaryResults');if(!q||q.trim().length<2){box.innerHTML='';return}beneficiaryTimer=setTimeout(async()=>{let api=apiUrl();if(!api){box.innerHTML='<p class="muted">Połączenie z Arkuszem Google jest chwilowo niedostępne.</p>';return}box.innerHTML='<p class="loading">Wyszukiwanie Beneficjentów…</p>';try{let res=await fetch(api+'?action=beneficiaries&q='+encodeURIComponent(q.trim()));let out=await res.json();if(!out.ok)throw new Error(out.error||'Błąd wyszukiwania');beneficiaryCache=out.items||[];box.innerHTML=beneficiaryCache.length?beneficiaryCache.map((b,i)=>`<button class="beneficiaryBtn" onclick="selectBeneficiary(${i})"><span class="personIcon">●</span><span class="beneficiaryText"><b>${escapeHtml(b.beneficjent)}</b><small>${escapeHtml(b.adres||'')} ${b.miejscowosc?'· '+escapeHtml(b.miejscowosc):''}</small><small><strong>${escapeHtml(b.rodzaj||'Zakres')}</strong> · ${escapeHtml(b.liczbaMod||'—')} modułów · ${escapeHtml(b.falownik||'falownik nieokreślony')} · ME ${escapeHtml(b.pojemnoscME||'—')}</small><small>Tel. ${escapeHtml(b.telefon||'brak')} ${b.sourceContract?'· Umowa '+escapeHtml(b.sourceContract):''}</small></span><span class="resultArrow">›</span></button>`).join(''):'<p class="muted resultEmpty">Nie znaleziono Beneficjenta.</p>'}catch(e){box.innerHTML='<p class="muted resultEmpty">Nie udało się pobrać danych: '+escapeHtml(e.message)+'</p>'}},350)}
function selectBeneficiary(i){let b=beneficiaryCache[i];Object.keys(b).forEach(k=>{if(b[k]!==''&&b[k]!=null)state[k]=b[k]});state.sourceBeneficiaryId=b.sourceBeneficiaryId;state.status='W trakcie';save();scheduleCloudSave(true);form()}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function scheduleCloudSave(now=false){clearTimeout(cloudTimer);let api=apiUrl();if(!api||!state.id)return;cloudTimer=setTimeout(()=>cloudAutosave(api),now?50:1800)}
async function cloudAutosave(api){try{let payload={...state,action:'autosave'};delete payload.photos;delete payload.map;delete payload.mapBg;delete payload.sig1;delete payload.sig2;let res=await fetch(api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});let out=await res.json();if(out.ok){state.status='W trakcie';state.dataZapisu=new Date().toLocaleString('pl-PL');localStorage.setItem('currentSurvey',JSON.stringify(state))}}catch(e){console.warn('Zapis Google niedostępny',e)}}
function newSurvey(){state={id:'GOL-'+new Date().getFullYear()+'-'+String(Date.now()).slice(-6),data:new Date().toISOString().slice(0,10)};photos=[];save();step=0;screen='form';render()}
function openForm(){screen='form';render()}function prev(){if(step){step--;render()}else goHome()}function next(){if(step===0&&!state.sourceBeneficiaryId){alert('Najpierw wybierz Beneficjenta z listy.');return}if(step<sections.length-1){step++;render()}else openMap()}function goHome(){screen='home';render()}function openMap(){screen='map';render()}function openPhotos(){screen='photos';render()}function openSign(){screen='sign';render()}function showSummary(){screen='summary';render()}
let tool='module',bg=null,items=[],drawing=false,start=null;
function mapEditor(){app.innerHTML=header('Mapa i moduły')+`<main class="wrap"><section class="card"><h2>Szkic rozmieszczenia</h2><div class="field"><label>Zdjęcie satelitarne / zdjęcie dachu</label><input id="mapFile" type="file" accept="image/*"></div><div class="tools">${[['crop','Wybierz wycinek'],['module','Moduł PV'],['dc','Trasa DC'],['ac','Trasa AC'],['device','Falownik / ME'],['erase','Usuń ostatni']].map(x=>`<button class="${tool===x[0]?'active':''}" onclick="setTool('${x[0]}')">${x[1]}</button>`).join('')}</div><div class="canvasWrap"><img id="mapBg" class="${bg?'':'hidden'}" src="${bg||''}"><canvas id="mapCanvas" width="720" height="430"></canvas></div><p class="muted">Wybierz „Wybierz wycinek” i zaznacz palcem fragment mapy albo zdjęcia. Następnie nanieś moduły PV, trasy AC/DC oraz urządzenia.</p></section></main><footer class="actions"><div><button class="btn" onclick="goHome()">Menu</button><button class="btn primary" onclick="saveMap();openPhotos()">Dalej</button></div></footer>`;setupCanvas()}
function setTool(t){tool=t;render()}function setupCanvas(){let c=document.querySelector('#mapCanvas'),ctx=c.getContext('2d');drawAll(ctx);document.querySelector('#mapFile').onchange=e=>{let r=new FileReader();r.onload=()=>{bg=r.result;items=[];render()};r.readAsDataURL(e.target.files[0])};let pos=e=>{let r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*c.width/r.width,y:(e.clientY-r.top)*c.height/r.height}};c.onpointerdown=e=>{drawing=true;start=pos(e)};c.onpointerup=e=>{if(!drawing)return;drawing=false;let p=pos(e);if(tool==='crop')cropBackground(start,p);else if(tool==='erase')items.pop();else items.push({tool,a:start,b:p});drawAll(ctx)}}
function cropBackground(a,b){if(!bg)return alert('Najpierw dodaj mapę lub zdjęcie.');let x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x),h=Math.abs(a.y-b.y);if(w<30||h<30)return;let img=new Image;img.onload=()=>{let out=document.createElement('canvas');out.width=720;out.height=430;out.getContext('2d').drawImage(img,x/720*img.width,y/430*img.height,w/720*img.width,h/430*img.height,0,0,720,430);bg=out.toDataURL('image/jpeg',.92);items=[];tool='module';render()};img.src=bg}
function drawAll(ctx){ctx.clearRect(0,0,720,430);items.forEach(o=>{ctx.lineWidth=6;ctx.strokeStyle=o.tool==='ac'?'#e22':o.tool==='dc'?'#1598df':o.tool==='module'?'#1d58bc':'#111';ctx.fillStyle=o.tool==='module'?'#2563caaa':'#fff8';if(o.tool==='module'||o.tool==='device'){let x=Math.min(o.a.x,o.b.x),y=Math.min(o.a.y,o.b.y),w=Math.abs(o.b.x-o.a.x),h=Math.abs(o.b.y-o.a.y);ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h)}else{ctx.beginPath();ctx.moveTo(o.a.x,o.a.y);ctx.lineTo(o.b.x,o.b.y);ctx.stroke()}})}
function saveMap(){state.map=document.querySelector('#mapCanvas').toDataURL();state.mapBg=bg;save()}
function photoScreen(){app.innerHTML=header('Zdjęcia')+`<main class="wrap"><section class="card"><h2>Dokumentacja zdjęciowa</h2><input id="photoInput" type="file" accept="image/*" capture="environment" multiple><p class="muted">Licznik, zabezpieczenie, rozdzielnica, dach, konstrukcja, falownik, magazyn energii i miejsce wpięcia.</p><div class="photos">${photos.map((p,i)=>`<div class="photo"><img src="${p}"></div>`).join('')}</div></section></main><footer class="actions"><div><button class="btn" onclick="openMap()">Wstecz</button><button class="btn primary" onclick="openSign()">Podpisy</button></div></footer>`;document.querySelector('#photoInput').onchange=e=>[...e.target.files].forEach(f=>{let r=new FileReader();r.onload=()=>{photos.push(r.result);state.photos=photos;save();photoScreen()};r.readAsDataURL(f)})}
function signatures(){app.innerHTML=header('Podpisy')+`<main class="wrap"><section class="card"><h2>Akceptacja Beneficjenta</h2><p>Beneficjent potwierdza zapoznanie się z ustaleniami wizji lokalnej, obowiązkami oraz zakresem planowanych prac.</p><div class="field"><label>Imię i nazwisko Beneficjenta</label><input data-k="podpisujacy" value="${state.podpisujacy||''}"></div><label>Podpis Beneficjenta</label><canvas class="sig" id="sig1" width="720" height="180"></canvas><button class="btn" onclick="clearSig('sig1')">Wyczyść</button><br><br><label>Podpis przedstawiciela Wykonawcy</label><canvas class="sig" id="sig2" width="720" height="180"></canvas><button class="btn" onclick="clearSig('sig2')">Wyczyść</button></section></main><footer class="actions"><div><button class="btn" onclick="openPhotos()">Wstecz</button><button class="btn primary" onclick="saveSigs();showSummary()">Podsumowanie</button></div></footer>`;bind();setupSig('sig1',state.sig1);setupSig('sig2',state.sig2)}
function setupSig(id,img){let c=document.querySelector('#'+id),x=c.getContext('2d');if(img){let i=new Image;i.onload=()=>x.drawImage(i,0,0,c.width,c.height);i.src=img}let down=false;c.onpointerdown=e=>{down=true;x.beginPath()};c.onpointermove=e=>{if(!down)return;let r=c.getBoundingClientRect();x.lineWidth=3;x.lineCap='round';x.lineTo((e.clientX-r.left)*c.width/r.width,(e.clientY-r.top)*c.height/r.height);x.stroke()};c.onpointerup=()=>down=false}function clearSig(id){let c=document.querySelector('#'+id);c.getContext('2d').clearRect(0,0,c.width,c.height)}function saveSigs(){state.sig1=document.querySelector('#sig1').toDataURL();state.sig2=document.querySelector('#sig2').toDataURL();state.akceptacja='TAK';state.dataPodpisu=new Date().toLocaleString('pl-PL');save()}
function summary(){let api=apiUrl(),mail=localStorage.getItem('defaultMail')||state.email||'';app.innerHTML=header('Podsumowanie')+`<main class="wrap"><div class="status" id="cloudStatus">Ankieta gotowa do zapisu i eksportu</div>${sections.map(([t,ks])=>`<section class="card"><h2>${t}</h2>${ks.map(k=>`<p><b>${labels[k]}:</b> ${state[k]||'—'}</p>`).join('')}</section>`).join('')}<section class="card"><h2>Mapa i podpisy</h2>${state.mapBg?`<img style="width:100%" src="${state.mapBg}">`:''}${state.map?`<img style="width:100%;margin-top:-100%;position:relative" src="${state.map}">`:''}${state.sig1?`<p>Podpis Beneficjenta</p><img style="width:100%" src="${state.sig1}">`:''}${state.sig2?`<p>Podpis Wykonawcy</p><img style="width:100%" src="${state.sig2}">`:''}</section><section class="card noPrint"><h2>Google i e-mail</h2><div class="field"><label>Wyślij PDF na e-mail</label><input id="emailTo" type="email" value="${mail}" placeholder="adres@firma.pl"></div><p class="muted">Połączenie z Arkuszem Google jest skonfigurowane.</p>${state.pdfUrl?`<p><a href="${state.pdfUrl}" target="_blank">Otwórz wygenerowany PDF</a></p>`:''}${state.folderUrl?`<p><a href="${state.folderUrl}" target="_blank">Otwórz folder na Dysku Google</a></p>`:''}</section><div class="export noPrint"><button class="btn primary" onclick="sendToGoogle()">Zapisz w Google, PDF i e-mail</button><button class="btn" onclick="window.print()">PDF lokalnie</button><button class="btn" onclick="exportExcel()">Eksport Excel</button><button class="btn" onclick="storeSurvey()">Zapisz offline</button><button class="btn danger" onclick="newSurvey()">Nowa ankieta</button></div></main><footer class="actions noPrint"><div><button class="btn" onclick="openSign()">Wstecz</button><button class="btn primary" onclick="goHome()">Menu</button></div></footer>`}
async function sendToGoogle(){let api=apiUrl(),emailTo=document.querySelector('#emailTo').value.trim(),status=document.querySelector('#cloudStatus');localStorage.setItem('defaultMail',emailTo);status.textContent='Wysyłanie danych i generowanie PDF…';try{let payload={...state,photos:state.photos||photos,emailTo};let res=await fetch(api,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});let out=await res.json();if(!out.ok)throw new Error(out.error||'Błąd usługi Google');state.status='Wysłana';state.pdfUrl=out.pdfUrl;state.folderUrl=out.folderUrl;state.dataZapisu=new Date().toLocaleString('pl-PL');save();storeSurvey(true);status.textContent='Zapisano w Google.';summary()}catch(e){status.textContent='Nie udało się wysłać. Dane nadal są zapisane na urządzeniu.';alert('Błąd wysyłki: '+e.message)}}
function storeSurvey(silent=false){let a=JSON.parse(localStorage.getItem('surveys')||'[]');a=a.filter(x=>x.id!==state.id);a.unshift({...state,photos:state.photos?.slice(0,8)});localStorage.setItem('surveys',JSON.stringify(a.slice(0,100)));if(!silent)alert('Ankieta zapisana offline')}
function loadSurvey(i){state=JSON.parse(localStorage.getItem('surveys')||'[]')[i];photos=state.photos||[];save();showSummary()}
function exportExcel(){let keys=Object.keys(labels),esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;');let rows=keys.map(k=>`<Row><Cell><Data ss:Type="String">${esc(labels[k])}</Data></Cell><Cell><Data ss:Type="String">${esc(state[k])}</Data></Cell></Row>`).join('');let xml=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Ankieta"><Table>${rows}</Table></Worksheet></Workbook>`;let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([xml],{type:'application/vnd.ms-excel'}));a.download=(state.id||'ankieta-wizji')+'.xls';a.click()}
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');render();
